version: "3"
services:
  db:
    container_name: postgres
    image: postgres:10
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ../data/redis:/data
